document.write("<h1 class='display-3'>Using Math class: </h1>")
document.write("<br>Power(5,2): "+Math.pow(5,2))
document.write("<br>Abs(-5.2): "+Math.abs(-5.2))
document.write("<br>ceil(5.2): "+Math.ceil(5.2))
document.write("<br>floor(5.2): "+Math.floor(5.2))
document.write("<br>round(5.2): "+Math.round(5.2))
document.write("<br>log(10): "+Math.log(10))
document.write("<br>random: "+Math.random())
document.write("<br>max(16,169): "+Math.max(16,169))
document.write("<br>min(16,169): "+Math.min(16,169))
document.write("<br>sin(90 deg): "+Math.sin(90*(Math.PI/180)))
document.write("<br>cos(90 deg): "+Math.cos(90*(Math.PI/180)))
document.write("<br>tan(90 deg): "+Math.tan(90*(Math.PI/180)))
document.write("<br>asin(0.5): "+Math.asin(0.5)*(180/Math.PI))
document.write("<br>acos(0.5): "+Math.acos(0.5)*(180/Math.PI))
document.write("<br>atan(0.5): "+Math.atan(0.5)*(180/Math.PI))

document.write("<br><br>")

document.write("<h1 class='display-3'>Using String class: </h1>")
var s = "Achha din hai aaj! "
document.write("<br>string: "+s)
document.write("<br>indexOf('a'): "+s.indexOf('a'))
document.write("<br>lastIndexOf('a'): "+s.lastIndexOf('a')+", lastIndexOf('z'): "+s.lastIndexOf('z')+", lastIndexOf(): "+s.lastIndexOf())
document.write("<br>charAt(6): "+s.charAt(6)+", charAt(): "+s.charAt()+", charAt(99): "+s.charAt(99))
document.write("<br>charCodeAt(6): "+s.charCodeAt(6)+", charCodeAt(): "+s.charCodeAt()+", charCodeAt(99): "+s.charCodeAt(99))
document.write("<br>concat(s): "+s.concat(s))
document.write("<br>fromCharCode(76): "+String.fromCharCode(76))
document.write("<br>includes('is'): "+s.includes('is'))
a = s.match("hai")
document.write("<br>match('is'): "+s.match('is')+", match('hai'): "+s.match('hai')+a)
console.log(s.match('hai'))
document.write("<br>search('is'): "+s.search('is')+", search('hai'): "+s.search('hai'))
s1=s.repeat(4)
document.write("<br>"+s1)
document.write("<br>replace:"+s.replace("hai", "tha"))
document.write("<br>slice: "+s.slice(5, 10))
document.write("<br>substring: "+s.substring(5,10))
document.write("<br>split: "+s.split("hai"))
str="AJANTA"
document.write("<br>string: "+str+", 1st occ of A: "+str.indexOf("A")+", last occ of A: "+str.lastIndexOf("A")+", substr btw them: "+str.substring(str.indexOf("A")+1,str.lastIndexOf("A")))

document.write("<br><br>")

document.write("<h1 class='display-3'>Using Date class: </h1>")
var d = new Date()
document.write("<br>date: "+d)
document.write("<br>getDate: "+d.getDate()) 
document.write("<br>getMonth (0-11): "+d.getMonth()) 
document.write("<br>getFullYear: "+d.getFullYear())
document.write("<br>getHours: "+d.getHours())
document.write("<br>getMinutes: "+d.getMinutes())
document.write("<br>getSeconds: "+d.getSeconds())
document.write("<br>getMilliseconds: "+d.getMilliseconds())
document.write("<br>getTime: "+d.getTime()) // (1/1/1970) 00:00:00 to till now
document.write("<br>getDay (0-6): "+d.getDay())
document.write("<br>toDateString: "+d.toDateString())
document.write("<br>toTimeString: "+d.toTimeString())
var oneday = 24*60*60*1000
document.write("<br>days passed till now: "+d.getTime()/oneday)
document.write("<br>years passed till now: "+d.getTime()/(365*oneday))

var d1 = new Date()
d1.setDate(3)
d1.setMonth(3)
d1.setFullYear(2020)
d1.setHours(21)
d1.setMinutes(30)
d1.setSeconds(0)
document.write("<br>set date: "+d1)

var d2 = new Date(2024,12,25)
document.write("<br>set date: "+d2)

document.write("<br><br><h1 class='display-6'>Date Task: </h1>")
var bday = new Date()
bday.setMonth(0)
bday.setDate(3)
bday.setFullYear(2025)
var today = new Date()
// days left for ur bday
if ((bday.getFullYear()<=today.getFullYear() && (bday.getMonth()<=today.getMonth()) && (bday.getDate()<today.getDate()))) {
    bday.setFullYear(bday.getFullYear()+1)
}
document.write("bday: "+bday.toDateString())
document.write("<br>today: "+today.toDateString())
document.write("<br>days left for ur bday: "+Math.floor((bday.getTime()-today.getTime())/oneday)+" days")